spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/examplesdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    restart:
      enabled: 'false'
    livereload:
      enabled: 'true'

  thymeleaf:
    cache: 'false'

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true

  web:
    resources:
      static-locations: classpath:/static/resources/
